---
title: Electricity Generation
---

```{r, include=FALSE}
suppressMessages(library(ggplot2))
suppressMessages(library(tidyverse))
library(readxl)
library(usmap)

fn <- "/base/inv/data/electricity/generation_monthly.xlsx"
gen <- read_excel(path=fn, sheet="2019_Final", skip=4)
colnames(gen) <- c("year", "month", "state", "type", "source", "MWh")
gen <- gen %>% filter(state != "US-Total")

fn <- "/base/inv/data/electricity/consumption_monthly.xlsx"
con <- read_excel(path=fn, sheet="2019_Final", skip=4)
colnames(con) <- c("year", "month", "state", "type", "source", "MWh")
con <- con %>% filter(state != "US-Total")

x <- gen %>%
   filter(source == "Total") %>%
   filter(type   == "Total Electric Power Industry")

# mag = cut(rank(generation), breaks=20, labels=F)
y <- x %>%
   group_by(state) %>%
   summarise(MWh = sum(MWh), .groups="drop") %>%
   mutate(mag = rank(-MWh))

tab <- y %>% 
   select(state, MWh) %>% 
   arrange(desc(MWh)) %>% 
   top_n(20, wt="MWh")

```

```{r, echo=FALSE, warning=F}
plot_usmap(data=y, values="mag", color="white") +
   scale_fill_continuous(
      low  = "red",
      high = "green",
      name = "rank",
   ) +
   theme(legend.position = "right")
```


```{r, echo=FALSE, results='asis'}
library(knitr)
kable(tab, caption="2019 Power Generation by State")
```


