---
title: Large Capitalization Stocks
---

```{r, include=FALSE}
library(RSQLite)
suppressMessages(library(ggplot2))
suppressMessages(library(lubridate))
suppressMessages(library(tidyverse))
suppressMessages(library(TTR))
suppressMessages(library(gridExtra))

# Get the SP500 prices from the database.
con <- dbConnect(SQLite(), dbname="/data/db")
dat <- dbGetQuery(con, "select * from eIndexLevels where name = 'SP500';")
dbDisconnect(con)

# Compute technical indicators and retain only recent data.
y <- data.frame(dat) %>% 
   select(-name) %>% 
   mutate(rsi  = RSI(cl), macd = MACD(cl)[,"macd"]) %>% 
   mutate(date = as.Date(date)) %>% 
   filter(date >= "2020-01-01")
```

```{r, echo=F, results='asis'}
latest <- y %>% pull(date) %>% tail(1)
datestr <- paste("Updated:", latest)
cat(datestr)
```


```{r, largecap, echo=FALSE}
p1 <- ggplot(y, aes(x=date, y=cl)) + 
   geom_line() +
   ylab("S&P 500 Index Level") +
   xlab("") 
p1

p2 <- ggplot(y, aes(x=date, y=rsi)) + 
   geom_line() +
   xlab("") +
   ylab("RSI(14)") +
   geom_hline(yintercept=70, col="red") +
   geom_hline(yintercept=30, col="blue")


p3 <- ggplot(y, aes(x=date, y=macd)) + 
   geom_line() +
   xlab("Date") +
   ylab("MACD(12,26)")


grid.arrange(p2, p3, nrow=2)
```


