---
title: "Sector Performance"
---

```{r, include=FALSE}
# Update database.
source("/Dropbox/ds/inv/data/sectors/01-getprices.R")
```

```{r, include=FALSE}
rm(list=ls())
library(readr)
library(RSQLite)
suppressMessages(library(ggplot2))
suppressMessages(library(tidyverse))
suppressMessages(library(lubridate))

# Get the ETF prices from the database.
con <- dbConnect(SQLite(), dbname="/data/db")
prices <- dbGetQuery(con, "select * from fse;")
dbDisconnect(con)

prices <- data.frame(prices) %>%
   mutate(date = as.Date(date)) %>%
   select(ticker, date, adjusted) %>%
   filter(date >= "2017-01-01") %>% 
   filter(ticker != "SP500") %>% 
   group_by(ticker) %>%
   mutate(price = adjusted / first(adjusted))

pp <- prices %>% mutate(ticker = substr(ticker, 2, 10))
latest <- pp %>% pull(date) %>% tail(1)
```

```{r, echo=FALSE}
ggplot(pp, aes(x=date, y=price, col=ticker)) + 
   geom_line()+ 
   labs(caption = paste("Updated:", latest))
```

```{R, include=FALSE}
P <- prices %>% select(date, ticker, price) %>%
   pivot_wider(names_from=ticker, values_from=price)

currdate <- P %>% slice(n()) %>% pull(date)
currprc  <- P %>% slice(n()) %>% select(starts_with("F"))
previous <- currdate - months(c(1, 3, 6, 12, 24, 36), abbreviate=F)
ndx <- rep(NA, length(previous))
R   <- NULL
for (k in 1:length(previous)) {
   i <- min(which.min(abs(P$date - previous[k])))
   p <- P[i,] %>% select(starts_with("F"))
   r <- currprc / p - 1
   R <- rbind(R, r)
}
R <- round(100 * R, 1) %>% t() %>% data.frame()
rownames(R) <- substr(rownames(R), 2, 10)
colnames(R) <- c("one month",
                 "three months",
                 "six months",
                 "one year",
                 "two years",
                 "three years")
R <- R %>% rownames_to_column("abbreviation")

a <- c("ENY", "MAT", "IDU", "UTY", "HLC", "NCL", "DIS", "STA", "TEC", "COM", "REL")
n <- c(
"Energy",
"Materials",
"Industrials",
"Utilities",
"Health Care",
"Financials",
"Consumer Discretionary",
"Consumer Staples",
"Information Technology",
"Communication Services",
"Real Estate")

secs <- data.frame(sector=n, abbreviation=a)
R <- full_join(secs, R, by="abbreviation")
```


```{r, echo=FALSE, results='asis'}
library(knitr)
kable(R, caption="Performance of Market Sectors")
```

