---
title: "Surveys of Sentiment"
output: pdf_document
---


```{r updatedatabase, include=FALSE}
# Update database.
# source("/Dropbox/ds/inv/data/sentiment/getData.R")
```


```{r, include=FALSE}
# Load necessary libraries.
rm(list=ls())
library(RSQLite)
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
suppressMessages(library(RcppRoll))

```

# University of Michigan Sentiment

```{r, include=FALSE}
con  <- dbConnect(SQLite(), dbname="/data/db")
qry  <- "select * from sent_michigan;"
mich <- dbGetQuery(con, qry)
dbDisconnect(con)

d <- mich %>%
   mutate(date = as.Date(date)) %>%
   filter(date >= "2010-01-01")
latest <- d %>% pull(date) %>% tail(1)

```

```{r, echo=FALSE}
ggplot(d) +
   geom_line(aes(x=date, y=value), color = "blue", lwd=1.3) +
   xlab("Date") +
   ylab("University of Michigan Sentiment") +
   labs(caption = paste("Updated:", Sys.Date(), 
                        "  Most recent data:", latest))

```

```{r, echo=FALSE, results='asis'}
library(knitr)
kable(tail(d, 6), 
      caption   = "Univessity of Michigan Sentiment",
      row.names = F)
```

# Duke University


```{r, include=FALSE}
con  <- dbConnect(SQLite(), dbname="/data/db")
qry  <- "select * from sent_duke;"
duke <- dbGetQuery(con, qry)
dbDisconnect(con)

d <- duke %>% 
   mutate(date = as.Date(date)) %>% 
   filter(date >= "2000-01-01") %>% select(date, econ, own) %>%
   pivot_longer(!date, names_to="subject")

```

```{r, echo=FALSE}
g <- ggplot(d, aes(x=date, y=value, col=subject)) +
   geom_line(lwd=1.2)
g
```

# AAII Sentiment Survey

The American Association of Individual Investors (AAII) Sentiment Indicator.

```{R,include=FALSE}
con <- dbConnect(SQLite(), dbname="/data/db")
qry <- "select * from sent_aaii;"
sentiment <- dbGetQuery(con, qry)
dbDisconnect(con)

d <- sentiment %>%
   mutate(date    = as.Date(date),
          overall = bullish - bearish,
          average = roll_meanr(overall, 13)) %>%
   drop_na() %>% 
   filter(date >= "2010-01-01")
```

```{r, echo=FALSE}
g <- ggplot(d) +
   geom_line(aes(x=date, y=average), color = "blue", lwd=1.3)  +
   geom_point(aes(x=date, y=overall))
g
```

```
