---
title: "Style Comparison"
---


```{r, include=FALSE}
options("getSymbols.warning4.0"=FALSE)
suppressMessages(library(quantmod))
suppressMessages(library(tidyverse))

vtwv <- getSymbols("VTWV", auto.assign=F)["2020/"][,6] # Small Value
vtwg <- getSymbols("VTWG", auto.assign=F)["2020/"][,6] # Small growth
vonv <- getSymbols("VONV", auto.assign=F)["2020/"][,6] # Large Value
vong <- getSymbols("VONG", auto.assign=F)["2020/"][,6] # Large growth

colnames(vtwv)[1] <- "SV"
colnames(vtwg)[1] <- "SG"
colnames(vonv)[1] <- "LV"
colnames(vong)[1] <- "LG"

rsv <- dailyReturn(vtwv); colnames(rsv)[1] <- "SV"
rsg <- dailyReturn(vtwg); colnames(rsg)[1] <- "SG"
rlv <- dailyReturn(vonv); colnames(rlv)[1] <- "LV"
rlg <- dailyReturn(vong); colnames(rlg)[1] <- "LG"

rs <- merge(rsv, rsg)
rl <- merge(rlv, rlg)
r  <- merge(rs, rl)

X <- apply(1+r, 2, cumprod) %>% 
   data.frame() %>% 
   rownames_to_column("date") %>% 
   mutate(date = as.Date(date)) %>% 
   pivot_longer(cols = starts_with(c("S", "L")), names_to = "style") %>% 
   mutate(style = str_replace_all(style, "\\.", " "))
latest <- X %>% pull(date) %>% tail(1)
```

```{r, echo=FALSE}
ggplot(X, aes(x=date, y=value, col=style)) + 
   geom_line()  +
   xlab("Date") +
   ylab("Cumulative Value") + 
   labs(caption = paste("Updated:", latest))
```

```{R, include=FALSE}
# Create table of performance
vtwv <- getSymbols("VTWV", auto.assign=F)["2018/"][,6] # Small Value
vtwg <- getSymbols("VTWG", auto.assign=F)["2018/"][,6] # Small growth
vonv <- getSymbols("VONV", auto.assign=F)["2018/"][,6] # Large Value
vong <- getSymbols("VONG", auto.assign=F)["2018/"][,6] # Large growth

colnames(vtwv)[1] <- "SV"
colnames(vtwg)[1] <- "SG"
colnames(vonv)[1] <- "LV"
colnames(vong)[1] <- "LG"

sml <- merge(vtwv, vtwg)
lrg <- merge(vonv, vong)
P   <- merge(sml, lrg)
P   <- data.frame(P)
dates <- rownames(P)
dates <- gsub("X", "", dates)
dates <- gsub("\\.", "-", dates, perl=T)
dates <- as.Date(dates)

currdate <- tail(dates, 1)
currprc  <- P %>% slice(n())
previous <- currdate - months(c(1, 3, 6, 12, 24, 36), abbreviate=F)
ndx <- rep(NA, length(previous))
R   <- NULL
for (k in 1:length(previous)) {
   i <- min(which.min(abs(dates - previous[k])))
   p <- P[i,]
   r <- currprc / p - 1
   R <- rbind(R, r)
}
R <- round(100 * R, 1) %>% t() %>% data.frame()
colnames(R) <- c("one month",
                 "three months",
                 "six months",
                 "one year",
                 "two years",
                 "three years")
#R <- R %>% rownames_to_column("abbreviation")
n <- c("Small Value", "Small Growth", "Large Value", "Large Growth")
R <- cbind(style=n, R)
```


```{r, echo=FALSE, results='asis'}
library(knitr)
kable(R, caption="Performance of Styles")
```
