---
title: "Interest Rates"
---


```{r, include=FALSE}
suppressMessages(library(quantmod))
suppressMessages(library(Quandl))
suppressMessages(library(ggplot2))
suppressMessages(library(lubridate))
suppressMessages(library(tidyverse))
options("getSymbols.warning4.0"=FALSE)

yc <- Quandl("USTREASURY/YIELD", api_key="NGPKkZ6sdNZyx6GeaVZT")
colnames(yc) <- c("date",
                  "M1", "M2", "M3", "M6",
                  "Y1", "Y2", "Y3", "Y5", "Y7", "Y10", "Y20", "Y30")
yc <- data.frame(yc) %>%
   arrange(date) %>%
   mutate(spread = Y10 - Y1) %>%
   filter(date >= "2017-01-01")

yend <- which(diff(yday(yc$date)) < 0)
yend <- c(yend, dim(yc)[1])
y    <- yc[yend,] %>%
   top_n(3, wt=date) %>%
   pivot_longer(cols     = starts_with(c("M", "Y")),
                names_to = "maturity")

ymonthly <- grep("M", y$maturity)
maturity <- parse_number(y$maturity)
maturity[ymonthly] <- maturity[ymonthly] / 12
y <- y %>% select(-maturity)
y <- y %>% add_column(maturity) %>% mutate(date=as.character(date))
latest <- y %>% pull(date) %>% tail(1)
```

## The Three-Month Treasury Bill Rate

```{r, echo=FALSE}
ggplot(yc, aes(x=date, y=M3)) +
   geom_line()  +
   xlab("Date") +
   ylab("Three-Month Treasury Bill Rate (%)") +
   ggtitle("Three-Month Treasury Bill Rate (%) since 2017") +
   labs(caption = paste("Updated:", latest))
```

## One- and Ten-Year Treasury Rates

```{r, echo=FALSE}
ytd <- yc %>% 
   filter(date > "2020-06-30") %>% 
   select(-spread) %>% 
   select(date, Y1, Y10) %>% 
   pivot_longer(!date, names_to="maturity", values_to="rate") 

ggplot(ytd, aes(x=date, y=rate, col=maturity)) +
   geom_line(size=1.5)  +
   xlab("Date") +
   ylab("Treasury Rate (%)") +
   ggtitle("One- and Ten-Year Treasury Rates (%) since Mid 2020") +
   labs(caption = paste("Updated:", latest))
```

## The Treasury Yield Spread

```{r, echo=FALSE}
ggplot(yc, aes(x=date, y=spread)) +
   geom_line()  +
   xlab("Date") +
   ylab("Treasury Yield Spread (10-year minus 1-year)")
```

## The TED Spread

```{r, include=FALSE}
ted <- getSymbols("TEDRATE", auto.assign=F, src="FRED")
ted <- ted["2017/"]
colnames(ted) <- c("TED")
ted <- data.frame(ted) %>%
   rownames_to_column("date") %>%
   mutate(date = as.Date(date)) %>%
   na.omit()
```

```{r, echo=FALSE}
ggplot(ted, aes(x=date, y=TED)) + geom_line() +
   ggtitle("TED Spread")
```


## The Yield Curve (Current and Previous Two Year Ends)

```{r, echo=FALSE}
ggplot(y, aes(x=maturity, y=value, col=date)) +
   geom_line(size=1.5)  +
   xlab("Maturity (years)") +
   ylab("Rate (%)")
```


